server:
  port: 9989
  context-path: /enditem
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/student?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /
      suffix:
  http:
    encoding:
      force: true
      charset: UTF-8

mybatis:
  type-aliases-package: com.baizhi.entity

